// IMPORTANT!
// This file has been automatically generated by "update-rules-index.ts",
// in order to update its content, update "update-rules-index.ts" and execute "npm run update"
import missingClientOnlyDirectiveValue from "./missing-client-only-directive-value.ts"
import noConflictSetDirectives from "./no-conflict-set-directives.ts"
import noDeprecatedAstroCanonicalurl from "./no-deprecated-astro-canonicalurl.ts"
import noDeprecatedAstroFetchcontent from "./no-deprecated-astro-fetchcontent.ts"
import noDeprecatedAstroResolve from "./no-deprecated-astro-resolve.ts"
import noDeprecatedGetentrybyslug from "./no-deprecated-getentrybyslug.ts"
import noExportsFromComponents from "./no-exports-from-components.ts"
import noPrerenderExportOutsidePages from "./no-prerender-export-outside-pages.ts"
import noSetHtmlDirective from "./no-set-html-directive.ts"
import noSetTextDirective from "./no-set-text-directive.ts"
import noUnsafeInlineScripts from "./no-unsafe-inline-scripts.ts"
import noUnusedCssSelector from "./no-unused-css-selector.ts"
import noUnusedDefineVarsInStyle from "./no-unused-define-vars-in-style.ts"
import preferClassListDirective from "./prefer-class-list-directive.ts"
import preferObjectClassList from "./prefer-object-class-list.ts"
import preferSplitClassList from "./prefer-split-class-list.ts"
import semi from "./semi.ts"
import sortAttributes from "./sort-attributes.ts"
import validCompile from "./valid-compile.ts"
import { buildA11yRules } from "../a11y/index.ts"
import type { RuleModule } from "../types.ts"

export const originalRules: RuleModule[] = [
  missingClientOnlyDirectiveValue,
  noConflictSetDirectives,
  noDeprecatedAstroCanonicalurl,
  noDeprecatedAstroFetchcontent,
  noDeprecatedAstroResolve,
  noDeprecatedGetentrybyslug,
  noExportsFromComponents,
  noPrerenderExportOutsidePages,
  noSetHtmlDirective,
  noSetTextDirective,
  noUnsafeInlineScripts,
  noUnusedCssSelector,
  noUnusedDefineVarsInStyle,
  preferClassListDirective,
  preferObjectClassList,
  preferSplitClassList,
  semi,
  sortAttributes,
  validCompile,
]
export const rules: RuleModule[] = [...originalRules, ...buildA11yRules()]
