import "./update-rules-index.ts"
import "./update-rulesets.ts"
import "./update-docs.ts"
import "./update-readme.ts"
import "./update-docs-rules-index.ts"
import "./update-types-for-node.ts"
import "./update-jsx-a11y-keys.ts"
