name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Packages
        run: npm install --legacy-peer-deps
      - name: build
        run: |
          npm run build
      - name: Lint
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm install --legacy-peer-deps
      - name: Test
        run: npm test
  test-for-eslint-v7:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install eslint v7
        run: |+
          npm i -D eslint@7 @typescript-eslint/parser@5 --legacy-peer-deps
          npx rimraf node_modules
      - name: Install Packages
        run: npm install --legacy-peer-deps
      - name: Test
        run: npm test
  test-for-node-v14:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install @typescript-eslint/parser v5
        run: |+
          npm i -D @typescript-eslint/parser@5 --legacy-peer-deps
          npx rimraf node_modules
      - name: Install Packages
        run: npm install --legacy-peer-deps
      - name: Test
        run: npm test
  test-and-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install Packages
        run: npm install --legacy-peer-deps
      - name: Test
        run: npm run cover
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@3b7078ee895f74fc267b7b267c88211df59fa816 # v2.2.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
