name: Close stale issues and PRs
on:
  schedule:
    - cron: "30 1 * * *"

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    if: github.repository == 'ota-meshi/eslint-plugin-astro'
    name: Close stale issues with missing information
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          any-of-labels: "needs repro,needs info,needs more info"
          days-before-stale: 60
          days-before-close: 14
          stale-issue-message: This issue is is stale because it missing information and has been open for 60 days with no activity.
          stale-pr-message: This PR is is stale because it missing information and has been open for 60 days with no activity.
          close-issue-message: >
            This issue has been automatically closed because we haven't received a
            response from the original author 🙈. This automation helps keep the issue
            tracker clean from issues that aren't actionable. Please reach out if you
            have more information for us! 🙂
          close-pr-message: >
            This PR has been automatically closed because we haven't received a
            response from the original author 🙈. This automation helps keep the issue
            tracker clean from PRs that aren't actionable. Please reach out if you
            have more information for us! 🙂
